# Generated by Django 2.2.5 on 2019-09-14 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Blogs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='articles.Article')),
                ('reply', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='articles.Comment')),
                ('user1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
