# Generated by Django 2.2.5 on 2019-09-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
